name: Deploy to GitHub Pages

permissions:
  contents: write
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        npm ci
        npm run-script build
        cp ./CNAME ./build/CNAME
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: html-dev
        
